baseURL = "https://chickenpopcorn.github.io/my-personal-blog/"
languageCode = "en-us"
title = "Jimmy's Blog"
theme = "minimal"
disqusShortname = "jimmyxie" # delete this to disable disqus comments
googleAnalytics = "UA-97195605-1"
publishDir = "docs"
canonifyURLs = true


[params]
    author = "Jimmy Xie"
    description = "This is my personal website and blog"
    githubUsername = "chickenPopcorn"
    accent = "Gray"
    showBorder = true
    backgroundColor = "WhiteSmoke"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-dark"
    highlightLanguages = ["go", "php", "css", "javascript", "html"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rxie25@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/chickenPopcorn/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rxie25/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jimmy-ruicong-xie-8b307929/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/7120964/ruicong-xie?tab=profile"
    name = "stack-overflow"
    weight = 5
